# Generated by Django 5.0.3 on 2024-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='humanorbot',
            field=models.BooleanField(default=True),
        ),
    ]
